"""empty message

Revision ID: 832cd3c654e4
Revises: 8a77937d12e5
Create Date: 2021-03-07 21:29:48.606295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832cd3c654e4'
down_revision = '8a77937d12e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plans_service_date_key', 'plans', type_='unique')
    op.drop_constraint('plans_service_name_key', 'plans', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('plans_service_name_key', 'plans', ['service_name'])
    op.create_unique_constraint('plans_service_date_key', 'plans', ['service_date'])
    # ### end Alembic commands ###
